2018-07-09 12:22:43,779 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 12:30:22,405 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 12:30:27,477 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 12:32:21,075 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 12:34:29,584 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 12:37:55,334 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 12:38:38,039 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 12:38:39,443 ERROR: Exception on /valves [GET] [in /home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seth/myproject/app/routes.py", line 201, in valves
    valves=valves.items)
AttributeError: 'list' object has no attribute 'items'
2018-07-09 12:42:44,430 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 12:42:47,244 ERROR: Exception on /valves [GET] [in /home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seth/myproject/app/routes.py", line 205, in valves
    valves = Valve.query_all().paginate(
AttributeError: type object 'Valve' has no attribute 'query_all'
2018-07-09 12:43:08,939 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 12:43:11,198 ERROR: Exception on /valves [GET] [in /home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/seth/myproject/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/seth/myproject/app/routes.py", line 205, in valves
    valves = Valve.query.all().paginate(
AttributeError: 'list' object has no attribute 'paginate'
2018-07-09 12:43:41,222 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 12:44:49,180 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 12:48:13,970 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
2018-07-09 12:50:11,007 INFO: Microblog startup [in /home/seth/myproject/app/__init__.py:46
